---
# API Gateway Service Level Objectives (SLOs)
# Based on Google SRE Workbook methodology

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-gateway-slo
  namespace: teei-prod
  labels:
    prometheus: kube-prometheus
    role: alert-rules
    service: api-gateway
spec:
  groups:
  - name: api-gateway-slo
    interval: 30s
    rules:

    # ─────────────────────────────────────────────────────────────
    # SLO 1: Availability ≥ 99.9% (3 nines)
    # ─────────────────────────────────────────────────────────────
    # Error budget: 43.2 minutes/month
    # Measurement: HTTP requests with 5xx status codes

    - record: slo:api_gateway:availability:ratio_rate5m
      expr: |
        (
          sum(rate(http_requests_total{service="api-gateway", status!~"5.."}[5m]))
          /
          sum(rate(http_requests_total{service="api-gateway"}[5m]))
        )

    - record: slo:api_gateway:availability:ratio_rate30m
      expr: |
        (
          sum(rate(http_requests_total{service="api-gateway", status!~"5.."}[30m]))
          /
          sum(rate(http_requests_total{service="api-gateway"}[30m]))
        )

    - record: slo:api_gateway:availability:ratio_rate1h
      expr: |
        (
          sum(rate(http_requests_total{service="api-gateway", status!~"5.."}[1h]))
          /
          sum(rate(http_requests_total{service="api-gateway"}[1h]))
        )

    - record: slo:api_gateway:availability:ratio_rate6h
      expr: |
        (
          sum(rate(http_requests_total{service="api-gateway", status!~"5.."}[6h]))
          /
          sum(rate(http_requests_total{service="api-gateway"}[6h]))
        )

    - record: slo:api_gateway:availability:ratio_rate1d
      expr: |
        (
          sum(rate(http_requests_total{service="api-gateway", status!~"5.."}[1d]))
          /
          sum(rate(http_requests_total{service="api-gateway"}[1d]))
        )

    - record: slo:api_gateway:availability:ratio_rate3d
      expr: |
        (
          sum(rate(http_requests_total{service="api-gateway", status!~"5.."}[3d]))
          /
          sum(rate(http_requests_total{service="api-gateway"}[3d]))
        )

    # Error budget burn rate alerts (multi-window, multi-burn-rate)
    # Alerting strategy from Google SRE Workbook Chapter 5

    # Page-worthy: Burn rate >14.4 (exhaust budget in 2 days)
    - alert: APIGatewayHighErrorBudgetBurn
      expr: |
        (
          slo:api_gateway:availability:ratio_rate1h < (1 - 14.4 * (1 - 0.999))
          and
          slo:api_gateway:availability:ratio_rate5m < (1 - 14.4 * (1 - 0.999))
        )
      for: 2m
      labels:
        severity: critical
        component: api-gateway
        slo: availability
        page: true
      annotations:
        summary: "API Gateway high error budget burn rate"
        description: "Availability SLO burn rate >14.4x (budget exhausted in 2 days)"
        current_availability: "{{ $value | humanizePercentage }}"
        target: "≥99.9%"
        runbook: "https://docs.teei.com/runbooks/slo/api-gateway-availability"

    # Ticket-worthy: Burn rate >6 (exhaust budget in 5 days)
    - alert: APIGatewayMediumErrorBudgetBurn
      expr: |
        (
          slo:api_gateway:availability:ratio_rate6h < (1 - 6 * (1 - 0.999))
          and
          slo:api_gateway:availability:ratio_rate30m < (1 - 6 * (1 - 0.999))
        )
      for: 15m
      labels:
        severity: warning
        component: api-gateway
        slo: availability
        page: false
      annotations:
        summary: "API Gateway medium error budget burn rate"
        description: "Availability SLO burn rate >6x (budget exhausted in 5 days)"
        current_availability: "{{ $value | humanizePercentage }}"
        target: "≥99.9%"

    # ─────────────────────────────────────────────────────────────
    # SLO 2: Latency P95 ≤ 100ms
    # ─────────────────────────────────────────────────────────────
    # Error budget: 5% of requests can exceed 100ms

    - record: slo:api_gateway:latency:p95_5m
      expr: |
        histogram_quantile(0.95,
          sum(rate(http_request_duration_seconds_bucket{service="api-gateway"}[5m])) by (le)
        )

    - record: slo:api_gateway:latency:p95_30m
      expr: |
        histogram_quantile(0.95,
          sum(rate(http_request_duration_seconds_bucket{service="api-gateway"}[30m])) by (le)
        )

    - record: slo:api_gateway:latency:p95_1h
      expr: |
        histogram_quantile(0.95,
          sum(rate(http_request_duration_seconds_bucket{service="api-gateway"}[1h])) by (le)
        )

    - record: slo:api_gateway:latency:p95_1d
      expr: |
        histogram_quantile(0.95,
          sum(rate(http_request_duration_seconds_bucket{service="api-gateway"}[1d])) by (le)
        )

    # Latency SLO violations
    - alert: APIGatewayLatencySLOViolation
      expr: |
        slo:api_gateway:latency:p95_1h > 0.1  # 100ms
      for: 10m
      labels:
        severity: warning
        component: api-gateway
        slo: latency
      annotations:
        summary: "API Gateway P95 latency exceeds 100ms"
        description: "Current P95 latency: {{ $value | humanizeDuration }}"
        target: "≤100ms"

    # ─────────────────────────────────────────────────────────────
    # SLO 3: Error Rate ≤ 1%
    # ─────────────────────────────────────────────────────────────

    - record: slo:api_gateway:error_rate:ratio_5m
      expr: |
        sum(rate(http_requests_total{service="api-gateway", status=~"5.."}[5m]))
        /
        sum(rate(http_requests_total{service="api-gateway"}[5m]))

    - record: slo:api_gateway:error_rate:ratio_1h
      expr: |
        sum(rate(http_requests_total{service="api-gateway", status=~"5.."}[1h]))
        /
        sum(rate(http_requests_total{service="api-gateway"}[1h]))

    - record: slo:api_gateway:error_rate:ratio_1d
      expr: |
        sum(rate(http_requests_total{service="api-gateway", status=~"5.."}[1d]))
        /
        sum(rate(http_requests_total{service="api-gateway"}[1d]))

    - alert: APIGatewayErrorRateSLOViolation
      expr: |
        slo:api_gateway:error_rate:ratio_1h > 0.01  # 1%
      for: 10m
      labels:
        severity: warning
        component: api-gateway
        slo: error-rate
      annotations:
        summary: "API Gateway error rate exceeds 1%"
        description: "Current error rate: {{ $value | humanizePercentage }}"
        target: "≤1%"

    # ─────────────────────────────────────────────────────────────
    # Error Budget Calculation
    # ─────────────────────────────────────────────────────────────

    - record: slo:api_gateway:error_budget:remaining_30d
      expr: |
        1 - (
          (1 - slo:api_gateway:availability:ratio_rate30d{})
          /
          (1 - 0.999)
        )

    - alert: APIGatewayErrorBudgetExhausted
      expr: |
        slo:api_gateway:error_budget:remaining_30d <= 0
      for: 5m
      labels:
        severity: critical
        component: api-gateway
        slo: error-budget
        page: true
      annotations:
        summary: "API Gateway 30-day error budget exhausted"
        description: "No error budget remaining for the month"
        action: "IMMEDIATE: Stop non-critical releases, focus on reliability"
