openapi: 3.0.3
info:
  title: TEEI Billing & Entitlements API
  description: |
    Billing service API for subscription management, License-to-Impact (L2I) bundles, and entitlement checks.

    **Founding-8 Licensing Tiers:**
    - **Essentials**: Basic features, limited capacity
    - **Professional**: Mid-tier with NLQ, Boardroom, connectors
    - **Enterprise**: Full features including Copilot, multi-region

    **L2I Bundles**: Add-on SKUs tied to TEEI program funding tiers
  version: 1.0.0
  contact:
    name: TEEI Platform Team
    email: platform@teei.io

servers:
  - url: http://localhost:3010
    description: Local development
  - url: https://api-staging.teei.io
    description: Staging
  - url: https://api.teei.io
    description: Production

tags:
  - name: Subscriptions
    description: Manage company subscriptions and plans
  - name: L2I Bundles
    description: License-to-Impact bundle purchases and allocations
  - name: Entitlements
    description: Feature access checks and quotas
  - name: Billing
    description: Invoices and usage tracking

paths:
  # Subscriptions
  /api/billing/subscriptions:
    post:
      tags: [Subscriptions]
      summary: Create subscription
      description: Create a new subscription for a company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscriptionRequest'
      responses:
        '200':
          description: Subscription created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  subscription:
                    $ref: '#/components/schemas/Subscription'
                  stripeClientSecret:
                    type: string
        '500':
          $ref: '#/components/responses/Error'

  /api/billing/subscriptions/{companyId}:
    get:
      tags: [Subscriptions]
      summary: Get company subscription
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Subscription found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  subscription:
                    $ref: '#/components/schemas/Subscription'
        '404':
          description: Subscription not found

  /api/billing/subscriptions/{subscriptionId}:
    patch:
      tags: [Subscriptions]
      summary: Update subscription
      description: Update subscription plan or seat count
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscriptionRequest'
      responses:
        '200':
          description: Subscription updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  subscription:
                    $ref: '#/components/schemas/Subscription'

  /api/billing/subscriptions/{subscriptionId}/cancel:
    post:
      tags: [Subscriptions]
      summary: Cancel subscription
      description: Cancel subscription at period end
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Subscription cancelled
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  subscription:
                    $ref: '#/components/schemas/Subscription'

  # L2I Bundles
  /api/billing/l2i/tiers:
    get:
      tags: [L2I Bundles]
      summary: Get L2I bundle tiers
      description: Get available L2I bundle tiers and pricing
      responses:
        '200':
          description: L2I tiers
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  tiers:
                    type: array
                    items:
                      $ref: '#/components/schemas/L2IBundleTierDefinition'

  /api/billing/l2i/bundles:
    post:
      tags: [L2I Bundles]
      summary: Purchase L2I bundle
      description: Purchase a License-to-Impact bundle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseL2IBundleRequest'
      responses:
        '200':
          description: Bundle purchased
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  bundle:
                    $ref: '#/components/schemas/L2IBundle'

  /api/billing/l2i/bundles/{companyId}:
    get:
      tags: [L2I Bundles]
      summary: Get company L2I bundles
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: L2I bundles
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  bundles:
                    type: array
                    items:
                      $ref: '#/components/schemas/L2IBundle'

  /api/billing/l2i/bundles/{companyId}/summary:
    get:
      tags: [L2I Bundles]
      summary: Get L2I bundle summary
      description: Get aggregate impact metrics and bundle summary
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Bundle summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  summary:
                    $ref: '#/components/schemas/L2IBundleSummary'

  /api/billing/l2i/allocations:
    post:
      tags: [L2I Bundles]
      summary: Allocate learner
      description: Allocate a learner to an L2I bundle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AllocateLearnerRequest'
      responses:
        '200':
          description: Learner allocated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  allocation:
                    $ref: '#/components/schemas/L2IAllocation'

  /api/billing/l2i/bundles/{bundleId}/allocations:
    get:
      tags: [L2I Bundles]
      summary: Get bundle allocations
      parameters:
        - name: bundleId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Bundle allocations
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  allocations:
                    type: array
                    items:
                      $ref: '#/components/schemas/L2IAllocation'

  # Entitlements
  /api/entitlements/me:
    get:
      tags: [Entitlements]
      summary: Get my entitlements
      description: Get entitlements for current user's company
      parameters:
        - name: companyId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: userId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Company entitlements
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  entitlements:
                    $ref: '#/components/schemas/CompanyEntitlements'

  /api/entitlements/check:
    post:
      tags: [Entitlements]
      summary: Check feature entitlement
      description: Check if a user/company has access to a feature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntitlementCheckRequest'
      responses:
        '200':
          description: Entitlement decision
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntitlementCheckResponse'

components:
  schemas:
    # Subscriptions
    CreateSubscriptionRequest:
      type: object
      required: [companyId, plan]
      properties:
        companyId:
          type: string
          format: uuid
        plan:
          type: string
          enum: [essentials, professional, enterprise, custom]
        seatCount:
          type: integer
          minimum: 1
          default: 1
        trialDays:
          type: integer
          minimum: 0
          maximum: 30
        paymentMethodId:
          type: string

    UpdateSubscriptionRequest:
      type: object
      properties:
        seatCount:
          type: integer
          minimum: 1
        plan:
          type: string
          enum: [essentials, professional, enterprise, custom]
        cancelAtPeriodEnd:
          type: boolean

    Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type: string
          format: uuid
        plan:
          type: string
          enum: [essentials, professional, enterprise, custom]
        status:
          type: string
          enum: [active, trialing, past_due, canceled, unpaid]
        seatCount:
          type: integer
        currentPeriodStart:
          type: string
          format: date-time
        currentPeriodEnd:
          type: string
          format: date-time
        cancelAtPeriodEnd:
          type: boolean

    # L2I Bundles
    L2IBundleTierDefinition:
      type: object
      properties:
        tier:
          type: string
          enum: [foundation, growth, expand, launch]
        name:
          type: string
        description:
          type: string
        priceUSD:
          type: integer
          description: Price in cents
        learnerCapacity:
          type: integer
        defaultRecognition:
          $ref: '#/components/schemas/RecognitionMetadata'
        availablePrograms:
          type: array
          items:
            type: string
            enum: [language, mentorship, upskilling, weei]

    RecognitionMetadata:
      type: object
      properties:
        founderBadge:
          type: string
          enum: [founding-8, founding-100, founding-1000]
        impactCredits:
          type: integer
        acknowledgmentTier:
          type: string
          enum: [bronze, silver, gold, platinum]
        publicRecognition:
          type: boolean

    PurchaseL2IBundleRequest:
      type: object
      required: [companyId, tier, programTags]
      properties:
        companyId:
          type: string
          format: uuid
        tier:
          type: string
          enum: [foundation, growth, expand, launch]
        programTags:
          type: array
          items:
            type: string
            enum: [language, mentorship, upskilling, weei]
          minItems: 1
        learnerCapacity:
          type: integer
        teeiProgramId:
          type: string
        allocationNotes:
          type: string
        paymentMethodId:
          type: string

    L2IBundle:
      type: object
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type: string
          format: uuid
        tier:
          type: string
          enum: [foundation, growth, expand, launch]
        sku:
          type: string
        priceUSD:
          type: integer
        learnerCapacity:
          type: integer
        learnersAllocated:
          type: integer
        programTags:
          type: array
          items:
            type: string
        recognition:
          $ref: '#/components/schemas/RecognitionMetadata'
        status:
          type: string
          enum: [active, expired, consumed, revoked]

    AllocateLearnerRequest:
      type: object
      required: [bundleId, learnerName, programTag]
      properties:
        bundleId:
          type: string
          format: uuid
        learnerName:
          type: string
        learnerEmail:
          type: string
          format: email
        learnerExternalId:
          type: string
        programTag:
          type: string
          enum: [language, mentorship, upskilling, weei]
        programCohort:
          type: string

    L2IAllocation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        bundleId:
          type: string
          format: uuid
        learnerName:
          type: string
        learnerEmail:
          type: string
        programTag:
          type: string
        status:
          type: string
          enum: [active, completed, withdrawn]
        allocatedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time

    L2IBundleSummary:
      type: object
      properties:
        totalBundles:
          type: integer
        totalCapacity:
          type: integer
        totalAllocated:
          type: integer
        totalSpent:
          type: integer
        impactCredits:
          type: integer
        founderBadge:
          type: string
          enum: [founding-8, founding-100, founding-1000]

    # Entitlements
    EntitlementCheckRequest:
      type: object
      required: [companyId, feature, action]
      properties:
        companyId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        feature:
          type: string
          enum: [report_builder, boardroom_live, forecast, benchmarking, nlq, gen_ai_reports, copilot, multi_region, connectors, api_access, sso, custom_branding, priority_support, export_pdf, export_csv, export_pptx]
        action:
          type: string
          enum: [view, create, update, delete, export, query, configure]

    EntitlementCheckResponse:
      type: object
      properties:
        success:
          type: boolean
        allowed:
          type: boolean
        reason:
          type: string
        quotaRemaining:
          type: integer
        expiresAt:
          type: string
          format: date-time

    CompanyEntitlements:
      type: object
      properties:
        companyId:
          type: string
          format: uuid
        subscription:
          type: object
          properties:
            plan:
              type: string
            status:
              type: string
            features:
              type: array
              items:
                type: string
            limits:
              type: object
              properties:
                maxSeats:
                  type: integer
                  nullable: true
                maxReportsPerMonth:
                  type: integer
                  nullable: true
                maxAiTokensPerMonth:
                  type: integer
                  nullable: true
                maxStorageGB:
                  type: integer
                  nullable: true
        l2iBundles:
          type: object
          properties:
            totalBundles:
              type: integer
            totalCapacity:
              type: integer
            totalAllocated:
              type: integer
            impactCredits:
              type: integer
            founderBadge:
              type: string
        availableFeatures:
          type: array
          items:
            type: string

  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: string
              message:
                type: string
