/**
 * AI Telemetry Types
 * Worker 10: AI/ML Explainability & Guardrails
 *
 * Types for OpenTelemetry spans and AI operation tracking
 */
import { z } from 'zod';
export declare const AIOperationSpanSchema: z.ZodObject<{
    spanId: z.ZodString;
    traceId: z.ZodString;
    parentSpanId: z.ZodOptional<z.ZodString>;
    operation: z.ZodEnum<["report-generation", "nlq-query", "q2q-classification", "other"]>;
    model: z.ZodString;
    provider: z.ZodString;
    startTime: z.ZodNumber;
    endTime: z.ZodOptional<z.ZodNumber>;
    durationMs: z.ZodOptional<z.ZodNumber>;
    tokensInput: z.ZodNumber;
    tokensOutput: z.ZodNumber;
    tokensTotal: z.ZodNumber;
    costUsd: z.ZodNumber;
    companyId: z.ZodString;
    userId: z.ZodOptional<z.ZodString>;
    requestId: z.ZodString;
    status: z.ZodEnum<["success", "error", "blocked"]>;
    error: z.ZodOptional<z.ZodString>;
    guardrailsPassed: z.ZodBoolean;
    safetyBlocked: z.ZodDefault<z.ZodBoolean>;
    evidenceBlocked: z.ZodDefault<z.ZodBoolean>;
    budgetBlocked: z.ZodDefault<z.ZodBoolean>;
    promptRecordId: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "error" | "success" | "blocked";
    companyId: string;
    spanId: string;
    traceId: string;
    operation: "other" | "report-generation" | "nlq-query" | "q2q-classification";
    model: string;
    provider: string;
    startTime: number;
    tokensInput: number;
    tokensOutput: number;
    tokensTotal: number;
    costUsd: number;
    requestId: string;
    guardrailsPassed: boolean;
    safetyBlocked: boolean;
    evidenceBlocked: boolean;
    budgetBlocked: boolean;
    error?: string | undefined;
    parentSpanId?: string | undefined;
    endTime?: number | undefined;
    durationMs?: number | undefined;
    userId?: string | undefined;
    promptRecordId?: string | undefined;
}, {
    status: "error" | "success" | "blocked";
    companyId: string;
    spanId: string;
    traceId: string;
    operation: "other" | "report-generation" | "nlq-query" | "q2q-classification";
    model: string;
    provider: string;
    startTime: number;
    tokensInput: number;
    tokensOutput: number;
    tokensTotal: number;
    costUsd: number;
    requestId: string;
    guardrailsPassed: boolean;
    error?: string | undefined;
    parentSpanId?: string | undefined;
    endTime?: number | undefined;
    durationMs?: number | undefined;
    userId?: string | undefined;
    safetyBlocked?: boolean | undefined;
    evidenceBlocked?: boolean | undefined;
    budgetBlocked?: boolean | undefined;
    promptRecordId?: string | undefined;
}>;
export type AIOperationSpan = z.infer<typeof AIOperationSpanSchema>;
export declare const AIMetricsSchema: z.ZodObject<{
    totalRequests: z.ZodNumber;
    successfulRequests: z.ZodNumber;
    failedRequests: z.ZodNumber;
    blockedRequests: z.ZodNumber;
    safetyBlocks: z.ZodNumber;
    evidenceBlocks: z.ZodNumber;
    budgetBlocks: z.ZodNumber;
    totalTokens: z.ZodNumber;
    totalInputTokens: z.ZodNumber;
    totalOutputTokens: z.ZodNumber;
    totalCostUsd: z.ZodNumber;
    avgCostPerRequest: z.ZodNumber;
    avgLatencyMs: z.ZodNumber;
    p50LatencyMs: z.ZodNumber;
    p95LatencyMs: z.ZodNumber;
    p99LatencyMs: z.ZodNumber;
    periodStart: z.ZodString;
    periodEnd: z.ZodString;
    companyId: z.ZodOptional<z.ZodString>;
    model: z.ZodOptional<z.ZodString>;
    operation: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    totalRequests: number;
    successfulRequests: number;
    failedRequests: number;
    blockedRequests: number;
    safetyBlocks: number;
    evidenceBlocks: number;
    budgetBlocks: number;
    totalTokens: number;
    totalInputTokens: number;
    totalOutputTokens: number;
    totalCostUsd: number;
    avgCostPerRequest: number;
    avgLatencyMs: number;
    p50LatencyMs: number;
    p95LatencyMs: number;
    p99LatencyMs: number;
    periodStart: string;
    periodEnd: string;
    companyId?: string | undefined;
    operation?: string | undefined;
    model?: string | undefined;
}, {
    totalRequests: number;
    successfulRequests: number;
    failedRequests: number;
    blockedRequests: number;
    safetyBlocks: number;
    evidenceBlocks: number;
    budgetBlocks: number;
    totalTokens: number;
    totalInputTokens: number;
    totalOutputTokens: number;
    totalCostUsd: number;
    avgCostPerRequest: number;
    avgLatencyMs: number;
    p50LatencyMs: number;
    p95LatencyMs: number;
    p99LatencyMs: number;
    periodStart: string;
    periodEnd: string;
    companyId?: string | undefined;
    operation?: string | undefined;
    model?: string | undefined;
}>;
export type AIMetrics = z.infer<typeof AIMetricsSchema>;
export declare const EvalFixtureSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    operation: z.ZodEnum<["report-generation", "nlq-query", "q2q-classification"]>;
    promptTemplate: z.ZodString;
    promptVariables: z.ZodRecord<z.ZodString, z.ZodAny>;
    evidenceSnippets: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        text: z.ZodString;
        dimension: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        id: string;
        text: string;
        dimension?: string | undefined;
    }, {
        id: string;
        text: string;
        dimension?: string | undefined;
    }>, "many">;
    expectedCitations: z.ZodOptional<z.ZodNumber>;
    expectedStructure: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>;
    goldenOutputPath: z.ZodOptional<z.ZodString>;
    seed: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    id: string;
    name: string;
    operation: "report-generation" | "nlq-query" | "q2q-classification";
    promptTemplate: string;
    promptVariables: Record<string, any>;
    evidenceSnippets: {
        id: string;
        text: string;
        dimension?: string | undefined;
    }[];
    seed: number;
    expectedCitations?: number | undefined;
    expectedStructure?: Record<string, any> | undefined;
    goldenOutputPath?: string | undefined;
}, {
    id: string;
    name: string;
    operation: "report-generation" | "nlq-query" | "q2q-classification";
    promptTemplate: string;
    promptVariables: Record<string, any>;
    evidenceSnippets: {
        id: string;
        text: string;
        dimension?: string | undefined;
    }[];
    expectedCitations?: number | undefined;
    expectedStructure?: Record<string, any> | undefined;
    goldenOutputPath?: string | undefined;
    seed?: number | undefined;
}>;
export type EvalFixture = z.infer<typeof EvalFixtureSchema>;
export declare const EvalResultSchema: z.ZodObject<{
    fixtureId: z.ZodString;
    fixtureName: z.ZodString;
    factualityScore: z.ZodNumber;
    structureScore: z.ZodNumber;
    safetyScore: z.ZodNumber;
    passed: z.ZodBoolean;
    errors: z.ZodArray<z.ZodString, "many">;
    warnings: z.ZodArray<z.ZodString, "many">;
    latencyMs: z.ZodNumber;
    tokensUsed: z.ZodNumber;
    costUsd: z.ZodNumber;
    model: z.ZodString;
    timestamp: z.ZodString;
}, "strip", z.ZodTypeAny, {
    timestamp: string;
    errors: string[];
    warnings: string[];
    model: string;
    costUsd: number;
    fixtureId: string;
    fixtureName: string;
    factualityScore: number;
    structureScore: number;
    safetyScore: number;
    passed: boolean;
    latencyMs: number;
    tokensUsed: number;
}, {
    timestamp: string;
    errors: string[];
    warnings: string[];
    model: string;
    costUsd: number;
    fixtureId: string;
    fixtureName: string;
    factualityScore: number;
    structureScore: number;
    safetyScore: number;
    passed: boolean;
    latencyMs: number;
    tokensUsed: number;
}>;
export type EvalResult = z.infer<typeof EvalResultSchema>;
export declare const EvalSuiteResultSchema: z.ZodObject<{
    suiteName: z.ZodString;
    totalFixtures: z.ZodNumber;
    passedFixtures: z.ZodNumber;
    failedFixtures: z.ZodNumber;
    avgFactualityScore: z.ZodNumber;
    avgStructureScore: z.ZodNumber;
    avgSafetyScore: z.ZodNumber;
    totalDurationMs: z.ZodNumber;
    totalCostUsd: z.ZodNumber;
    results: z.ZodArray<z.ZodObject<{
        fixtureId: z.ZodString;
        fixtureName: z.ZodString;
        factualityScore: z.ZodNumber;
        structureScore: z.ZodNumber;
        safetyScore: z.ZodNumber;
        passed: z.ZodBoolean;
        errors: z.ZodArray<z.ZodString, "many">;
        warnings: z.ZodArray<z.ZodString, "many">;
        latencyMs: z.ZodNumber;
        tokensUsed: z.ZodNumber;
        costUsd: z.ZodNumber;
        model: z.ZodString;
        timestamp: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        timestamp: string;
        errors: string[];
        warnings: string[];
        model: string;
        costUsd: number;
        fixtureId: string;
        fixtureName: string;
        factualityScore: number;
        structureScore: number;
        safetyScore: number;
        passed: boolean;
        latencyMs: number;
        tokensUsed: number;
    }, {
        timestamp: string;
        errors: string[];
        warnings: string[];
        model: string;
        costUsd: number;
        fixtureId: string;
        fixtureName: string;
        factualityScore: number;
        structureScore: number;
        safetyScore: number;
        passed: boolean;
        latencyMs: number;
        tokensUsed: number;
    }>, "many">;
    timestamp: z.ZodString;
    model: z.ZodString;
}, "strip", z.ZodTypeAny, {
    timestamp: string;
    model: string;
    totalCostUsd: number;
    suiteName: string;
    totalFixtures: number;
    passedFixtures: number;
    failedFixtures: number;
    avgFactualityScore: number;
    avgStructureScore: number;
    avgSafetyScore: number;
    totalDurationMs: number;
    results: {
        timestamp: string;
        errors: string[];
        warnings: string[];
        model: string;
        costUsd: number;
        fixtureId: string;
        fixtureName: string;
        factualityScore: number;
        structureScore: number;
        safetyScore: number;
        passed: boolean;
        latencyMs: number;
        tokensUsed: number;
    }[];
}, {
    timestamp: string;
    model: string;
    totalCostUsd: number;
    suiteName: string;
    totalFixtures: number;
    passedFixtures: number;
    failedFixtures: number;
    avgFactualityScore: number;
    avgStructureScore: number;
    avgSafetyScore: number;
    totalDurationMs: number;
    results: {
        timestamp: string;
        errors: string[];
        warnings: string[];
        model: string;
        costUsd: number;
        fixtureId: string;
        fixtureName: string;
        factualityScore: number;
        structureScore: number;
        safetyScore: number;
        passed: boolean;
        latencyMs: number;
        tokensUsed: number;
    }[];
}>;
export type EvalSuiteResult = z.infer<typeof EvalSuiteResultSchema>;
//# sourceMappingURL=telemetry.d.ts.map