/**
 * Auto-generated TypeScript types from OpenAPI v1 specifications
 * DO NOT EDIT MANUALLY - Generated by openapi-typescript-codegen
 */

// ==================== COMMON TYPES ====================

export interface Pagination {
  page: number;
  limit: number;
  total: number;
  hasNext: boolean;
  hasPrev?: boolean;
  totalPages?: number;
}

export interface ApiError {
  error: string;
  message?: string;
  details?: Record<string, any>;
}

// ==================== REPORTING TYPES ====================

export interface GenerateReportRequest {
  companyId: string;
  period: {
    start: string; // ISO date
    end: string; // ISO date
  };
  locale?: 'en' | 'es' | 'fr';
  sections: ('impact-summary' | 'sroi-narrative' | 'outcome-trends')[];
  deterministic?: boolean;
  temperature?: number; // 0-2
  maxTokens?: number; // 100-8000
}

export interface Citation {
  id: string;
  snippetId: string;
  text: string;
  relevanceScore?: number;
}

export interface ReportSection {
  type: string;
  content: string;
  citations: Citation[];
  wordCount: number;
  characterCount: number;
}

export interface LineageMetadata {
  modelName: string;
  promptVersion: string;
  timestamp: string;
  tokensUsed: number;
  tokensInput: number;
  tokensOutput: number;
  estimatedCostUsd: string;
}

export interface GenerateReportResponse {
  reportId: string;
  sections: ReportSection[];
  lineage: LineageMetadata;
  warnings?: string[];
}

export interface ModelCostBreakdown {
  modelName: string;
  requestsCount: number;
  totalCostUsd: string;
  totalTokens: number;
}

export interface CostSummaryResponse {
  totalCostUsd: string;
  requestsCount: number;
  totalTokens: number;
  avgCostPerRequest: string;
  byModel: ModelCostBreakdown[];
}

// ==================== ANALYTICS TYPES ====================

export type TimeInterval = 'day' | 'week' | 'month' | 'quarter' | 'year';
export type CohortDimension = 'program' | 'region' | 'age_group' | 'gender' | 'enrollment_month';
export type FunnelType = 'enrollment' | 'engagement' | 'completion' | 'outcome_progression';
export type PeerGroup = 'industry' | 'size' | 'region' | 'all';

export interface TrendsQuery {
  companyId: string;
  metrics: string; // Comma-separated
  startDate: string;
  endDate: string;
  interval?: TimeInterval;
  groupBy?: string;
  filters?: Record<string, any>;
  page?: number;
  limit?: number;
}

export interface TrendsResponse {
  data: Record<string, any>[];
  pagination: Pagination;
  metadata: {
    companyId: string;
    interval: string;
    queryDurationMs: number;
    cacheHit: boolean;
  };
}

export interface CohortsQuery {
  companyId: string;
  metrics: string;
  cohortDimension: CohortDimension;
  startDate: string;
  endDate: string;
  filters?: Record<string, any>;
}

export interface CohortData {
  cohort: string;
  participantsCount: number;
  [metric: string]: any;
}

export interface CohortsResponse {
  data: CohortData[];
  metadata: {
    companyId: string;
    cohortDimension: string;
    periodStart: string;
    periodEnd: string;
    queryDurationMs: number;
  };
}

export interface FunnelsQuery {
  companyId: string;
  funnelType: FunnelType;
  startDate: string;
  endDate: string;
  groupBy?: string;
}

export interface FunnelStage {
  stage: string;
  count: number;
  percentage: number;
  dropoffRate: number;
}

export interface FunnelsResponse {
  data: {
    stages: FunnelStage[];
    overallConversionRate: number;
  };
  metadata: {
    companyId: string;
    funnelType: string;
    periodStart: string;
    periodEnd: string;
    queryDurationMs: number;
  };
}

export interface BenchmarksQuery {
  companyId: string;
  metrics: string;
  peerGroup?: PeerGroup;
  period?: string;
}

export type PerformanceLevel =
  | 'well_below_average'
  | 'below_average'
  | 'average'
  | 'above_average'
  | 'well_above_average';

export interface BenchmarkMetric {
  metric: string;
  companyValue: number;
  peerMedian: number;
  peerP25: number;
  peerP75: number;
  percentile: number;
  performance: PerformanceLevel;
}

export interface BenchmarksResponse {
  data: {
    companyMetrics: Record<string, number>;
    benchmarks: BenchmarkMetric[];
  };
  metadata: {
    companyId: string;
    peerGroup: string;
    period: string;
    peerCount: number;
    queryDurationMs: number;
  };
}

// ==================== IMPACT-IN TYPES ====================

export type DeliveryProvider = 'benevity' | 'goodera' | 'workday';
export type DeliveryStatus = 'pending' | 'success' | 'failed' | 'retrying';

export interface Delivery {
  id: string;
  deliveryId: string;
  companyId: string;
  provider: DeliveryProvider;
  status: DeliveryStatus;
  attemptCount: number;
  payload: Record<string, any>;
  lastError?: string | null;
  providerResponse?: Record<string, any> | null;
  deliveredAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ListDeliveriesQuery {
  companyId?: string;
  provider?: DeliveryProvider;
  status?: DeliveryStatus;
  startDate?: string;
  endDate?: string;
  page?: number;
  limit?: number;
}

export interface DeliveryListResponse {
  data: Delivery[];
  pagination: Pagination;
}

export interface DeliveryDetailResponse {
  data: Delivery;
}

export interface ReplayResponse {
  success: boolean;
  message: string;
  newStatus?: 'success' | 'failed';
  error?: string;
}

export interface BulkReplayRequest {
  ids: string[]; // 1-100 UUIDs
}

export interface BulkReplayResult {
  id: string;
  success: boolean;
  newStatus?: 'success' | 'failed';
  error?: string;
}

export interface BulkReplayResponse {
  summary: {
    total: number;
    successful: number;
    failed: number;
  };
  results: BulkReplayResult[];
}

export interface StatsResponse {
  data: {
    overall: {
      total: number;
      successful: number;
      failed: number;
      pending: number;
      retrying: number;
    };
    byProvider: Array<{
      provider: DeliveryProvider;
      status: DeliveryStatus;
      count: number;
      avgAttempts: number;
    }>;
  };
}

// ==================== NOTIFICATIONS TYPES ====================

export type NotificationType = 'email' | 'sms' | 'push';
export type NotificationChannel = 'sendgrid' | 'twilio' | 'fcm';
export type NotificationStatus = 'queued' | 'sent' | 'failed' | 'scheduled' | 'cancelled';

export interface SendNotificationRequest {
  companyId?: string;
  userId?: string;
  type: NotificationType;
  templateId: string;
  recipient: string;
  subject?: string;
  payload: Record<string, any>;
}

export interface ScheduleNotificationRequest extends SendNotificationRequest {
  scheduledAt: string; // ISO datetime
}

export interface SendNotificationResponse {
  success: boolean;
  notificationId: string;
  status: 'queued';
  message: string;
}

export interface ScheduleNotificationResponse {
  success: boolean;
  notificationId: string;
  scheduledAt: string;
  message: string;
}

export interface CancelNotificationResponse {
  success: boolean;
  message: string;
}

export interface NotificationHistoryItem {
  id: string;
  type: NotificationType;
  templateId: string;
  recipient: string;
  status: NotificationStatus;
  scheduledAt?: string | null;
  sentAt?: string | null;
  failureReason?: string | null;
  retryCount: number;
  createdAt: string;
}

export interface NotificationHistoryQuery {
  companyId?: string;
  userId?: string;
  type?: NotificationType;
  status?: NotificationStatus;
  limit?: number;
  offset?: number;
}

export interface NotificationHistoryResponse {
  success: boolean;
  notifications: NotificationHistoryItem[];
  pagination: {
    limit: number;
    offset: number;
    total: number;
  };
}

export interface DeliveryReceipt {
  id: string;
  eventType: string;
  eventData: Record<string, any>;
  receivedAt: string;
}

export interface NotificationDetail {
  id: string;
  type: NotificationType;
  channel: NotificationChannel;
  templateId: string;
  recipient: string;
  subject?: string | null;
  status: NotificationStatus;
  scheduledAt?: string | null;
  sentAt?: string | null;
  failureReason?: string | null;
  retryCount: number;
  createdAt: string;
}

export interface NotificationDetailResponse {
  success: boolean;
  notification: NotificationDetail;
  deliveryReceipts: DeliveryReceipt[];
}

export interface QuotaDetail {
  limit: number;
  used: number;
  remaining: number;
  resetAt: string;
}

export interface QuotaResponse {
  success: boolean;
  companyId: string;
  quotas: {
    email: QuotaDetail;
    sms: QuotaDetail;
    push: QuotaDetail;
  };
}
