/**
 * Base Tile Aggregator
 * Common utilities for tile aggregation
 */

import { db } from '@teei/shared-schema';
import { TileMetadata } from '@teei/shared-types';

/**
 * Default period for tile calculations (current quarter)
 */
export function getDefaultPeriod(): { start: string; end: string } {
  const now = new Date();
  const currentQuarter = Math.floor(now.getMonth() / 3);
  const startMonth = currentQuarter * 3;

  const startDate = new Date(now.getFullYear(), startMonth, 1);
  const endDate = new Date(now.getFullYear(), startMonth + 3, 0); // Last day of quarter

  return {
    start: startDate.toISOString().split('T')[0],
    end: endDate.toISOString().split('T')[0],
  };
}

/**
 * Generate tile metadata
 */
export function generateTileMetadata(
  companyId: string,
  programType: 'language' | 'mentorship' | 'upskilling' | 'weei',
  period: { start: string; end: string },
  freshness: 'realtime' | 'cached_5m' | 'cached_1h' | 'cached_24h' = 'cached_1h'
): Omit<TileMetadata, 'tileId'> {
  return {
    tileId: '', // Will be generated by caller
    companyId,
    programType,
    period,
    calculatedAt: new Date().toISOString(),
    dataFreshness: freshness,
  };
}

/**
 * Calculate percentage safely (avoid division by zero)
 */
export function calculateRate(numerator: number, denominator: number): number {
  if (denominator === 0) return 0;
  return Math.min(numerator / denominator, 1); // Cap at 1.0 (100%)
}

/**
 * Calculate average safely
 */
export function calculateAverage(values: number[]): number {
  if (values.length === 0) return 0;
  const sum = values.reduce((acc, val) => acc + val, 0);
  return sum / values.length;
}

/**
 * Round to 2 decimal places
 */
export function round(value: number, decimals: number = 2): number {
  return Math.round(value * Math.pow(10, decimals)) / Math.pow(10, decimals);
}

/**
 * Get weeks between two dates
 */
export function getWeeksBetween(start: string, end: string): number {
  const startDate = new Date(start);
  const endDate = new Date(end);
  const diffTime = Math.abs(endDate.getTime() - startDate.getTime());
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return Math.ceil(diffDays / 7);
}

/**
 * Get days between two dates
 */
export function getDaysBetween(start: string, end: string): number {
  const startDate = new Date(start);
  const endDate = new Date(end);
  const diffTime = Math.abs(endDate.getTime() - startDate.getTime());
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
}

/**
 * Filter data by company and period
 * This is a placeholder - in production, you'd join with company enrollment data
 */
export function isInPeriod(date: Date | null, period: { start: string; end: string }): boolean {
  if (!date) return false;
  const dateStr = date.toISOString().split('T')[0];
  return dateStr >= period.start && dateStr <= period.end;
}

/**
 * Get VIS score for a company/period (stub - calls impact-calculator service)
 */
export async function getVISForPeriod(
  companyId: string,
  period: { start: string; end: string }
): Promise<number | undefined> {
  // TODO: Call impact-calculator service or query metrics table
  // For now, return undefined to indicate VIS is not available
  return undefined;
}

/**
 * Get SROI score for a company/period (stub - calls analytics service)
 */
export async function getSROIForPeriod(
  companyId: string,
  period: { start: string; end: string }
): Promise<number | undefined> {
  // TODO: Call SROI calculator or query metrics table
  // For now, return undefined to indicate SROI is not available
  return undefined;
}
